interface Records {
  image: string;
  name: string;
  date: string;
  project: string;
  assignHour: number;
  hour: number;
  description: string;
}

const records: Records[] = [
  {
    image: "https://i.ibb.co/wgHdwHd/unnamed.png",
    name: "John Doe Web Designer",
    date: "1 Jan 2023",
    project: "Video Calling App",
    assignHour: 20,
    hour: 12,
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
  },
  {
    image: "https://i.ibb.co/0CtKFMx/channels4-profile.jpg",
    name: "John Doe Web Designer",
    date: "1 Jan 2023",
    project: "Video Calling App",
    assignHour: 20,
    hour: 12,
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
  },
  {
    image: "https://i.ibb.co/QDxJ0N5/istockphoto-656673020-612x612.jpg",
    name: "Richard Miles Android Developer",
    date: "1 Jan 2023",
    project: "Project Management",
    assignHour: 10,
    hour: 12,
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
  },
  {
    image: "https://i.ibb.co/2P4kwYR/jack-finnigan-rri-AI0nhcbc-unsplash-1.jpg",
    name: "Jeffery Lalor Team Leader",
    date: "1 Jan 2023",
    project: "Ware House Development",
    assignHour: 10,
    hour: 12,
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
  },
  {
    image: "https://i.ibb.co/wgHdwHd/unnamed.png",
    name: "Jeffrey Warden Web Develope",
    date: "1 Jan 2023",
    project: "Project Management",
    assignHour: 10,
    hour: 12,
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
  },
  {
    image: "https://i.ibb.co/2P4kwYR/jack-finnigan-rri-AI0nhcbc-unsplash-1.jpg",
    name: "John Doe Web Designer",
    date: "1 Jan 2023",
    project: "Office Management",
    assignHour: 10,
    hour: 12,
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
  },
  {
    image: "https://i.ibb.co/wgHdwHd/unnamed.png",
    name: "John Smith Android Developer",
    date: "1 Jan 2023",
    project: "Video Calling App",
    assignHour: 10,
    hour: 12,
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
  },
  {
    image: "https://i.ibb.co/QDxJ0N5/istockphoto-656673020-612x612.jpg",
    name: "Lesley Grauer Team Leader",
    date: "1 Jan 2023",
    project: "Hospital Administration",
    assignHour: 10,
    hour: 12,
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
  },
  {
    image: "https://i.ibb.co/BtH5szD/petr-sevcovic-e12w-QLAj-Qi0-unsplash.jpg",
    name: "Loren Gatlin Android Developer",
    date: "1 Jan 2023",
    project: "Office Management",
    assignHour: 10,
    hour: 12,
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
  },
  {
    image: "https://i.ibb.co/wgHdwHd/unnamed.png",
    name: "Mike Litorus Android DeveloperIOS Developer",
    date: "1 Jan 2023",
    project: "Hospital Administration",
    assignHour: 10,
    hour: 12,
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
  },
  {
    image: "https://i.ibb.co/wgHdwHd/unnamed.png",
    name: "John Doe Web Designer",
    date: "1 Jan 2023",
    project: "Video Calling App",
    assignHour: 20,
    hour: 12,
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
  },
  {
    image: "https://i.ibb.co/0CtKFMx/channels4-profile.jpg",
    name: "John Doe Web Designer",
    date: "1 Jan 2023",
    project: "Video Calling App",
    assignHour: 20,
    hour: 12,
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
  },
  {
    image: "https://i.ibb.co/QDxJ0N5/istockphoto-656673020-612x612.jpg",
    name: "Richard Miles Android Developer",
    date: "1 Jan 2023",
    project: "Project Management",
    assignHour: 10,
    hour: 12,
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
  },
  {
    image: "https://i.ibb.co/2P4kwYR/jack-finnigan-rri-AI0nhcbc-unsplash-1.jpg",
    name: "Jeffery Lalor Team Leader",
    date: "1 Jan 2023",
    project: "Ware House Development",
    assignHour: 10,
    hour: 12,
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
  },
  {
    image: "https://i.ibb.co/wgHdwHd/unnamed.png",
    name: "Jeffrey Warden Web Develope",
    date: "1 Jan 2023",
    project: "Project Management",
    assignHour: 10,
    hour: 12,
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
  },
  {
    image: "https://i.ibb.co/2P4kwYR/jack-finnigan-rri-AI0nhcbc-unsplash-1.jpg",
    name: "John Doe Web Designer",
    date: "1 Jan 2023",
    project: "Office Management",
    assignHour: 10,
    hour: 12,
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
  },
  {
    image: "https://i.ibb.co/wgHdwHd/unnamed.png",
    name: "John Smith Android Developer",
    date: "1 Jan 2023",
    project: "Video Calling App",
    assignHour: 10,
    hour: 12,
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
  },
  {
    image: "https://i.ibb.co/QDxJ0N5/istockphoto-656673020-612x612.jpg",
    name: "Lesley Grauer Team Leader",
    date: "1 Jan 2023",
    project: "Hospital Administration",
    assignHour: 10,
    hour: 12,
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
  },
  {
    image: "https://i.ibb.co/wgHdwHd/unnamed.png",
    name: "Loren Gatlin Android Developer",
    date: "1 Jan 2023",
    project: "Office Management",
    assignHour: 10,
    hour: 12,
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
  },
  {
    image: "https://i.ibb.co/wgHdwHd/unnamed.png",
    name: "Mike Litorus Android DeveloperIOS Developer",
    date: "1 Jan 2023",
    project: "Hospital Administration",
    assignHour: 10,
    hour: 12,
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
  },
  {
    image: "https://i.ibb.co/wgHdwHd/unnamed.png",
    name: "John Doe Web Designer",
    date: "1 Jan 2023",
    project: "Video Calling App",
    assignHour: 20,
    hour: 12,
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
  },
  {
    image: "https://i.ibb.co/0CtKFMx/channels4-profile.jpg",
    name: "John Doe Web Designer",
    date: "1 Jan 2023",
    project: "Video Calling App",
    assignHour: 20,
    hour: 12,
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
  },
  {
    image: "https://i.ibb.co/QDxJ0N5/istockphoto-656673020-612x612.jpg",
    name: "Richard Miles Android Developer",
    date: "1 Jan 2023",
    project: "Project Management",
    assignHour: 10,
    hour: 12,
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
  },
  {
    image: "https://i.ibb.co/2P4kwYR/jack-finnigan-rri-AI0nhcbc-unsplash-1.jpg",
    name: "Jeffery Lalor Team Leader",
    date: "1 Jan 2023",
    project: "Ware House Development",
    assignHour: 10,
    hour: 12,
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
  },
  {
    image: "https://i.ibb.co/wgHdwHd/unnamed.png",
    name: "Jeffrey Warden Web Develope",
    date: "1 Jan 2023",
    project: "Project Management",
    assignHour: 10,
    hour: 12,
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
  },
  {
    image: "https://i.ibb.co/2P4kwYR/jack-finnigan-rri-AI0nhcbc-unsplash-1.jpg",
    name: "John Doe Web Designer",
    date: "1 Jan 2023",
    project: "Office Management",
    assignHour: 10,
    hour: 12,
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
  },
  {
    image: "https://i.ibb.co/wgHdwHd/unnamed.png",
    name: "John Smith Android Developer",
    date: "1 Jan 2023",
    project: "Video Calling App",
    assignHour: 10,
    hour: 12,
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
  },
  {
    image: "https://i.ibb.co/QDxJ0N5/istockphoto-656673020-612x612.jpg",
    name: "Lesley Grauer Team Leader",
    date: "1 Jan 2023",
    project: "Hospital Administration",
    assignHour: 10,
    hour: 12,
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
  },
  {
    image: "https://i.ibb.co/wgHdwHd/unnamed.png",
    name: "Loren Gatlin Android Developer",
    date: "1 Jan 2023",
    project: "Office Management",
    assignHour: 10,
    hour: 12,
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
  },
  {
    image: "https://i.ibb.co/wgHdwHd/unnamed.png",
    name: "Mike Litorus Android DeveloperIOS Developer",
    date: "1 Jan 2023",
    project: "Hospital Administration",
    assignHour: 10,
    hour: 12,
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
  },
  {
    image: "https://i.ibb.co/wgHdwHd/unnamed.png",
    name: "John Doe Web Designer",
    date: "1 Jan 2023",
    project: "Video Calling App",
    assignHour: 20,
    hour: 12,
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
  },
  {
    image: "https://i.ibb.co/0CtKFMx/channels4-profile.jpg",
    name: "John Doe Web Designer",
    date: "1 Jan 2023",
    project: "Video Calling App",
    assignHour: 20,
    hour: 12,
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
  },
  {
    image: "https://i.ibb.co/QDxJ0N5/istockphoto-656673020-612x612.jpg",
    name: "Richard Miles Android Developer",
    date: "1 Jan 2023",
    project: "Project Management",
    assignHour: 10,
    hour: 12,
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
  },
  {
    image: "https://i.ibb.co/2P4kwYR/jack-finnigan-rri-AI0nhcbc-unsplash-1.jpg",
    name: "Jeffery Lalor Team Leader",
    date: "1 Jan 2023",
    project: "Ware House Development",
    assignHour: 10,
    hour: 12,
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
  },
  {
    image: "https://i.ibb.co/wgHdwHd/unnamed.png",
    name: "Jeffrey Warden Web Develope",
    date: "1 Jan 2023",
    project: "Project Management",
    assignHour: 10,
    hour: 12,
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
  },
  {
    image: "https://i.ibb.co/2P4kwYR/jack-finnigan-rri-AI0nhcbc-unsplash-1.jpg",
    name: "John Doe Web Designer",
    date: "1 Jan 2023",
    project: "Office Management",
    assignHour: 10,
    hour: 12,
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
  },
  {
    image: "https://i.ibb.co/wgHdwHd/unnamed.png",
    name: "John Smith Android Developer",
    date: "1 Jan 2023",
    project: "Video Calling App",
    assignHour: 10,
    hour: 12,
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
  },
  {
    image: "https://i.ibb.co/QDxJ0N5/istockphoto-656673020-612x612.jpg",
    name: "Lesley Grauer Team Leader",
    date: "1 Jan 2023",
    project: "Hospital Administration",
    assignHour: 10,
    hour: 12,
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
  },
  {
    image: "https://i.ibb.co/wgHdwHd/unnamed.png",
    name: "Loren Gatlin Android Developer",
    date: "1 Jan 2023",
    project: "Office Management",
    assignHour: 10,
    hour: 12,
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
  },
  {
    image: "https://i.ibb.co/wgHdwHd/unnamed.png",
    name: "Mike Litorus Android DeveloperIOS Developer",
    date: "1 Jan 2023",
    project: "Hospital Administration",
    assignHour: 10,
    hour: 12,
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
  },
  {
    image: "https://i.ibb.co/wgHdwHd/unnamed.png",
    name: "John Doe Web Designer",
    date: "1 Jan 2023",
    project: "Video Calling App",
    assignHour: 20,
    hour: 12,
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
  },
  {
    image: "https://i.ibb.co/0CtKFMx/channels4-profile.jpg",
    name: "John Doe Web Designer",
    date: "1 Jan 2023",
    project: "Video Calling App",
    assignHour: 20,
    hour: 12,
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
  },
  {
    image: "https://i.ibb.co/QDxJ0N5/istockphoto-656673020-612x612.jpg",
    name: "Richard Miles Android Developer",
    date: "1 Jan 2023",
    project: "Project Management",
    assignHour: 10,
    hour: 12,
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
  },
  {
    image: "https://i.ibb.co/2P4kwYR/jack-finnigan-rri-AI0nhcbc-unsplash-1.jpg",
    name: "Jeffery Lalor Team Leader",
    date: "1 Jan 2023",
    project: "Ware House Development",
    assignHour: 10,
    hour: 12,
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
  },
  {
    image: "https://i.ibb.co/wgHdwHd/unnamed.png",
    name: "Jeffrey Warden Web Develope",
    date: "1 Jan 2023",
    project: "Project Management",
    assignHour: 10,
    hour: 12,
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
  },
  {
    image: "https://i.ibb.co/2P4kwYR/jack-finnigan-rri-AI0nhcbc-unsplash-1.jpg",
    name: "John Doe Web Designer",
    date: "1 Jan 2023",
    project: "Office Management",
    assignHour: 10,
    hour: 12,
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
  },
  {
    image: "https://i.ibb.co/wgHdwHd/unnamed.png",
    name: "John Smith Android Developer",
    date: "1 Jan 2023",
    project: "Video Calling App",
    assignHour: 10,
    hour: 12,
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
  },
  {
    image: "https://i.ibb.co/QDxJ0N5/istockphoto-656673020-612x612.jpg",
    name: "Lesley Grauer Team Leader",
    date: "1 Jan 2023",
    project: "Hospital Administration",
    assignHour: 10,
    hour: 12,
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
  },
  {
    image: "https://i.ibb.co/wgHdwHd/unnamed.png",
    name: "Loren Gatlin Android Developer",
    date: "1 Jan 2023",
    project: "Office Management",
    assignHour: 10,
    hour: 12,
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
  },
  {
    image: "https://i.ibb.co/BtH5szD/petr-sevcovic-e12w-QLAj-Qi0-unsplash.jpg",
    name: "Mike Litorus Android DeveloperIOS Developer",
    date: "1 Jan 2023",
    project: "Hospital Administration",
    assignHour: 10,
    hour: 12,
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
  },
  {
    image: "https://i.ibb.co/wgHdwHd/unnamed.png",
    name: "John Doe Web Designer",
    date: "1 Jan 2023",
    project: "Video Calling App",
    assignHour: 20,
    hour: 12,
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
  },
  {
    image: "https://i.ibb.co/0CtKFMx/channels4-profile.jpg",
    name: "John Doe Web Designer",
    date: "1 Jan 2023",
    project: "Video Calling App",
    assignHour: 20,
    hour: 12,
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
  },
  {
    image: "https://i.ibb.co/QDxJ0N5/istockphoto-656673020-612x612.jpg",
    name: "Richard Miles Android Developer",
    date: "1 Jan 2023",
    project: "Project Management",
    assignHour: 10,
    hour: 12,
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
  },
  {
    image: "https://i.ibb.co/2P4kwYR/jack-finnigan-rri-AI0nhcbc-unsplash-1.jpg",
    name: "Jeffery Lalor Team Leader",
    date: "1 Jan 2023",
    project: "Ware House Development",
    assignHour: 10,
    hour: 12,
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
  },
  {
    image: "https://i.ibb.co/wgHdwHd/unnamed.png",
    name: "Jeffrey Warden Web Develope",
    date: "1 Jan 2023",
    project: "Project Management",
    assignHour: 10,
    hour: 12,
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
  },
  {
    image: "https://i.ibb.co/2P4kwYR/jack-finnigan-rri-AI0nhcbc-unsplash-1.jpg",
    name: "John Doe Web Designer",
    date: "1 Jan 2023",
    project: "Office Management",
    assignHour: 10,
    hour: 12,
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
  },
  {
    image: "https://i.ibb.co/wgHdwHd/unnamed.png",
    name: "John Smith Android Developer",
    date: "1 Jan 2023",
    project: "Video Calling App",
    assignHour: 10,
    hour: 12,
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
  },
  {
    image: "https://i.ibb.co/QDxJ0N5/istockphoto-656673020-612x612.jpg",
    name: "Lesley Grauer Team Leader",
    date: "1 Jan 2023",
    project: "Hospital Administration",
    assignHour: 10,
    hour: 12,
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
  },
  {
    image: "https://i.ibb.co/wgHdwHd/unnamed.png",
    name: "Loren Gatlin Android Developer",
    date: "1 Jan 2023",
    project: "Office Management",
    assignHour: 10,
    hour: 12,
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
  },
  {
    image: "https://i.ibb.co/wgHdwHd/unnamed.png",
    name: "Mike Litorus Android DeveloperIOS Developer",
    date: "1 Jan 2023",
    project: "Hospital Administration",
    assignHour: 10,
    hour: 12,
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
  },
];

export { records };
